# Generated by Django 5.2.8 on 2025-11-16 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251116_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('email_confirm', 'Email Confirmation')], default='login', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'OTP Token',
                'verbose_name_plural': 'OTP Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='accessrequest',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Access Request', 'verbose_name_plural': 'Access Requests'},
        ),
        migrations.AlterModelOptions(
            name='availabilityreport',
            options={'ordering': ['-date', '-submitted_at'], 'verbose_name': 'Availability Report', 'verbose_name_plural': 'Availability Reports'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availabilityreport',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments'),
        ),
        migrations.AlterField(
            model_name='availabilityreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID number', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='User must be approved by admin to access system'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['status', 'submitted_at'], name='core_access_status_6598a3_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityreport',
            index=models.Index(fields=['user', 'date'], name='core_availa_user_id_805847_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityreport',
            index=models.Index(fields=['date', 'status'], name='core_availa_date_a14400_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['unit', 'role'], name='core_profil_unit_id_eb7c81_idx'),
        ),
        migrations.AddField(
            model_name='otptoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['user', 'used', 'expires_at'], name='core_otptok_user_id_84e1be_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['token', 'used'], name='core_otptok_token_14106a_idx'),
        ),
    ]
