# Generated by Django 5.2.7 on 2025-11-23 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otptoken_alter_accessrequest_options_and_more'),
    ]

    operations = [
        # Add rejection_reason to AccessRequest
        migrations.AddField(
            model_name='accessrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable'),
        ),
        # Alter approved_by field to fix related_name
        migrations.AlterField(
            model_name='accessrequest',
            name='approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_requests',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Add updated_at to AvailabilityReport
        migrations.AddField(
            model_name='availabilityreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Alter date field to add db_index
        migrations.AlterField(
            model_name='availabilityreport',
            name='date',
            field=models.DateField(db_index=True),
        ),
        # Alter status field
        migrations.AlterField(
            model_name='availabilityreport',
            name='status',
            field=models.CharField(
                choices=[
                    ('available', 'Available'),
                    ('unavailable', 'Unavailable'),
                    ('partial', 'Partial Availability'),
                    ('pending', 'Pending'),
                ],
                default='pending',
                max_length=50
            ),
        ),
        # Alter submitted_at to add db_index
        migrations.AlterField(
            model_name='availabilityreport',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        # Add unique_together constraint
        migrations.AlterUniqueTogether(
            name='availabilityreport',
            unique_together={('user', 'date')},
        ),
        # Add created_at and updated_at to Profile
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Alter role field to use choices
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(
                choices=[
                    ('user', 'User'),
                    ('team_manager', 'Team Manager'),
                    ('section_manager', 'Section Manager'),
                    ('branch_manager', 'Branch Manager'),
                    ('unit_manager', 'Unit Manager'),
                    ('admin', 'Admin'),
                ],
                default='user',
                max_length=50
            ),
        ),
        # Add fields to Unit
        migrations.AddField(
            model_name='unit',
            name='code',
            field=models.CharField(
                blank=True,
                help_text='Unique organizational code',
                max_length=50,
                null=True,
                unique=True
            ),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_he',
            field=models.CharField(
                blank=True,
                help_text='Hebrew name',
                max_length=200
            ),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(
                choices=[
                    ('unit', 'Unit'),
                    ('branch', 'Branch'),
                    ('section', 'Section'),
                    ('team', 'Team'),
                ],
                default='unit',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Alter name field to add db_index
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        # Alter parent field to add related_name
        migrations.AlterField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='core.unit'
            ),
        ),
        # Add created_at and updated_at to User
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Add index for Unit (parent, unit_type)
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(
                fields=['parent', 'unit_type'],
                name='core_unit_parent__d6342f_idx'
            ),
        ),
    ]
