# Generated by Django 5.2.7 on 2025-11-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_created_at_alter_unit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('team_manager', 'Team Manager'), ('section_manager', 'Section Manager'), ('branch_manager', 'Branch Manager'), ('unit_manager', 'Unit Manager'), ('admin', 'Admin'), ('system_manager', 'System Manager')], default='user', max_length=50),
        ),
    ]
