# Generated by Django 5.2.7 on 2025-11-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_system_manager_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='שם העיר/הישוב', max_length=200)),
                ('name_he', models.CharField(blank=True, help_text='שם בעברית', max_length=200)),
                ('location_type', models.CharField(choices=[('city', 'עיר'), ('town', 'ישוב'), ('kibbutz', 'קיבוץ'), ('moshav', 'מושב')], default='city', max_length=20)),
                ('region', models.CharField(blank=True, help_text="אזור (צפון, מרכז, דרום וכו')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'מיקום',
                'verbose_name_plural': 'מיקומים',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'location_type'], name='core_locati_name_22f44a_idx')],
            },
        ),
        migrations.AddField(
            model_name='availabilityreport',
            name='location',
            field=models.ForeignKey(blank=True, help_text='מיקום (עיר/ישוב/קיבוץ)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.location'),
        ),
    ]
