# Generated by Django 5.2.7 on 2025-11-27 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='כתובת מגורים', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='עיר מגורים', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='core.location'),
        ),
    ]
