# Generated by Django 5.2.7 on 2025-11-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_address_and_city_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityreport',
            name='location_text',
            field=models.CharField(blank=True, help_text='מיקום טקסטואלי (בסיס, בית, או מיקום אחר)', max_length=200),
        ),
    ]
