# Generated by Django 5.2.7 on 2025-12-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_location_text_to_availability_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
