# Generated by Django 5.2.7 on 2025-12-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_name',
            field=models.CharField(blank=True, help_text='שם איש קשר', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='טלפון איש קשר', max_length=20),
        ),
    ]
