# Generated by Django 5.2.7 on 2025-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_contact_name_profile_contact_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order_number', 'name'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AddField(
            model_name='unit',
            name='order_number',
            field=models.IntegerField(default=0, help_text='Order for sorting siblings'),
        ),
    ]
