"""
Django settings for yirok_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-4neg@ylhj(joq+-p45#%(5^4427^icvur**+1b3rz+(+#4g85)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*'] if os.getenv('ALLOWED_HOSTS') == '*' else (os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else [])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'import_export',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yirok_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'core', 'email_templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yirok_project.wsgi.application'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Supabase Transaction Pooler (PgBouncer) Configuration
# Using pooler to avoid IPv6 issues on Render
# Pool Mode: Transaction
# Connection parameters:
#   host: aws-1-ap-southeast-2.pooler.supabase.com
#   port: 6543
#   database: postgres
#   user: postgres.fhikehkuookglfjomxen
#   pool_mode: transaction

import logging
logger = logging.getLogger('django')

# Support both DATABASE_URL and individual environment variables
# Environment variable names can be lowercase (as in user's example) or uppercase
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Parse DATABASE_URL if provided
    # Format: postgresql://user:pass@host:port/dbname?params
    import urllib.parse
    try:
        parsed = urllib.parse.urlparse(DATABASE_URL)
        DB_NAME = parsed.path[1:] if parsed.path else 'postgres'
        DB_USER = parsed.username
        DB_PASS = parsed.password
        DB_HOST = parsed.hostname
        DB_PORT = str(parsed.port) if parsed.port else '6543'
        
        # Parse query parameters for sslmode
        query_params = urllib.parse.parse_qs(parsed.query)
        sslmode = query_params.get('sslmode', ['require'])[0]
        
        logger.info(f"[DB CONFIG] Using DATABASE_URL from environment")
        
        # Validate all required fields from DATABASE_URL
        if not all([DB_NAME, DB_USER, DB_PASS, DB_HOST]):
            raise ValueError("DATABASE_URL is missing required components (user, password, or host)")
            
    except Exception as e:
        logger.error(f"[DB CONFIG] Failed to parse DATABASE_URL: {e}")
        raise ValueError(f"Invalid DATABASE_URL format: {e}")
else:
    # Use individual environment variables (support both uppercase and lowercase)
    # Try uppercase first, then lowercase
    DB_NAME = os.getenv('DB_NAME') or os.getenv('dbname')
    DB_USER = os.getenv('DB_USER') or os.getenv('user')
    DB_PASS = os.getenv('DB_PASS') or os.getenv('password')
    DB_HOST = os.getenv('DB_HOST') or os.getenv('host')
    DB_PORT = os.getenv('DB_PORT') or os.getenv('port') or '6543'
    sslmode = 'require'
    
    # Log which environment variable names are being used
    db_name_source = 'DB_NAME' if os.getenv('DB_NAME') else ('dbname' if os.getenv('dbname') else 'NOT SET')
    db_user_source = 'DB_USER' if os.getenv('DB_USER') else ('user' if os.getenv('user') else 'NOT SET')
    db_pass_source = 'DB_PASS' if os.getenv('DB_PASS') else ('password' if os.getenv('password') else 'NOT SET')
    db_host_source = 'DB_HOST' if os.getenv('DB_HOST') else ('host' if os.getenv('host') else 'NOT SET')
    db_port_source = 'DB_PORT' if os.getenv('DB_PORT') else ('port' if os.getenv('port') else 'default')
    
    logger.info(f"[DB CONFIG] Reading from env vars: {db_name_source}, {db_user_source}, {db_pass_source}, {db_host_source}, {db_port_source}")
    
    # Validate required credentials are set
    if not DB_NAME:
        raise ValueError("Database name not set. Please set DB_NAME or dbname environment variable.")
    if not DB_USER:
        raise ValueError("Database user not set. Please set DB_USER or user environment variable.")
    if not DB_PASS:
        raise ValueError("Database password not set. Please set DB_PASS or password environment variable.")
    if not DB_HOST:
        raise ValueError("Database host not set. Please set DB_HOST or host environment variable.")

# Log database configuration (without password)
logger.info(f"[DB CONFIG] Using Supabase Transaction Pooler (IPv4 compatible, pool_mode: transaction)")
logger.info(f"[DB CONFIG] DB_NAME (database): {DB_NAME}")
logger.info(f"[DB CONFIG] DB_USER (user): {DB_USER}")
logger.info(f"[DB CONFIG] DB_HOST (host): {DB_HOST}")
logger.info(f"[DB CONFIG] DB_PORT (port): {DB_PORT}")
logger.info(f"[DB CONFIG] DB_PASS (password): {'*' * len(DB_PASS) if DB_PASS else 'NOT SET'} (length: {len(DB_PASS) if DB_PASS else 0})")
logger.info(f"[DB CONFIG] SSL Mode: {sslmode}")
logger.info(f"[DB CONFIG] Pool Mode: transaction")

# Validate password format (should be 16 characters for Supabase)
if DB_PASS and len(DB_PASS) != 16:
    logger.warning(f"[DB CONFIG] WARNING: Password length is {len(DB_PASS)}, expected 16 for Supabase. Check for extra spaces or incorrect password.")

# Configure PostgreSQL connection with Transaction Pooler
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASS,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'OPTIONS': {
            'sslmode': sslmode,  # Supabase requires SSL
            'connect_timeout': 10,  # 10 second timeout
        },
        'CONN_MAX_AGE': 600,  # Reuse connections for 10 minutes
    }
}

logger.info(f"[DB CONFIG] Database configured: {DB_USER}@{DB_HOST}:{DB_PORT}/{DB_NAME} (SSL: {sslmode}, Pool: transaction)")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
# Use console backend in development if EMAIL_BACKEND is not set
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.sendgrid.net')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'apikey')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@yirok.com')

# Django REST Framework
from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# JWT Settings
from rest_framework_simplejwt.settings import api_settings

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# CORS Settings
# Allow frontend to access API
cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
if cors_origins_env:
    # Split by comma and strip whitespace
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',') if origin.strip()]
else:
    # Default to localhost for development
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ]

# Also allow any origin in development (for testing)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Log CORS configuration
logger.info(f"[CORS CONFIG] Allowed origins: {CORS_ALLOWED_ORIGINS}")
logger.info(f"[CORS CONFIG] Allow all origins (DEBUG mode): {CORS_ALLOW_ALL_ORIGINS if DEBUG else False}")

# Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {funcName} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',  # Changed to DEBUG to see all logs
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # Changed to DEBUG
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # Log all SQL queries
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # Always DEBUG for core app
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # Log all requests
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Sentry Configuration (optional)
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.1,
        send_default_pii=True,
    )

# Rate Limiting (simple in-memory cache for OTP)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# OTP Rate Limiting
OTP_RATE_LIMIT = int(os.getenv('OTP_RATE_LIMIT', 5))  # Max 5 OTP requests per hour per user
OTP_EXPIRY_MINUTES = int(os.getenv('OTP_EXPIRY_MINUTES', 10))
